# Generated by Django 5.0.6 on 2024-05-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lecturaRFID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo', models.CharField(max_length=8)),
                ('tag_id', models.CharField(max_length=24)),
                ('length', models.IntegerField()),
                ('ant', models.IntegerField()),
                ('cnt', models.IntegerField()),
                ('rssi', models.IntegerField()),
                ('nombre_herramienta', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'una nueva lectura RFID',
                'verbose_name_plural': 'Lecturas RFID de herramientas',
            },
        ),
        migrations.CreateModel(
            name='nombreEtiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta_id', models.CharField(max_length=100, unique=True)),
                ('nombre_herramienta', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'un identificador de etiqueta de codigo',
                'verbose_name_plural': 'Identificadores de etiquetas de códigos',
            },
        ),
        migrations.CreateModel(
            name='seleccionarRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carpeta_excel', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'la ruta de lectura',
                'verbose_name_plural': 'Configuración de la ruta de lectura',
            },
        ),
    ]
