# Generated by Django 5.0.6 on 2024-05-16 16:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturarfid',
            name='fecha_modificacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecturarfid',
            name='nombre_archivo',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
