# Generated by Django 5.0.6 on 2024-05-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_lecturarfid_fecha_modificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturarfid',
            name='length',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='lecturarfid',
            name='nombre_archivo',
            field=models.CharField(max_length=255),
        ),
    ]
