# Generated by Django 5.0.6 on 2024-05-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_alter_lecturarfid_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturarfid',
            name='rssi',
            field=models.CharField(max_length=10),
        ),
    ]
