# Generated by Django 5.0.6 on 2024-05-29 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_alter_lecturarfid_rssi'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturarfid',
            name='estado',
            field=models.CharField(choices=[('no_especificado', 'No especificado'), ('disponible', 'Disponible'), ('no_disponible_obra', 'No disponible (en obra)'), ('no_disponible_malogrado', 'No disponible (malogrado)')], default='no_especificado', max_length=23),
        ),
    ]
