# Generated by Django 5.0.6 on 2024-05-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_lecturarfid_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturarfid',
            name='estado',
            field=models.CharField(choices=[('no_especificado', 'No especificado'), ('disponible', 'Disponible'), ('no_disponible_obra', 'No disponible (en obra)'), ('no_disponible_malogrado', 'No disponible (malogrado)')], default='disponible', max_length=23),
        ),
    ]
